version: "3.3"

services:
  api:
    build: .
    container_name: rodel-vita-api
    ports:
      - "8001:8000"
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_USER=rodelsoft
      - MYSQL_PASSWORD=RodelS0ft3566#
      - MYSQL_DB=rodel_vita
    volumes:
      - ./app:/app
    networks:
      - rodel-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
  api-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8002:8000"
    environment:
      - ENV=production

  frontend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python frontend.py
    depends_on:
      - api

networks:
  rodel-net:
    driver: bridge